packages/frontend/src/boot/main-boot.ts
=> fix: dキーを押して目がやられる問題

packages/frontend/src/scripts/get-user-menu.ts
=> feat: user qrcode

packages/frontend/src/components/MkQrcode.vue, packages/frontend/src/pages/follow-me.vue, packages/frontend/src/router/definition.ts, packages/frontend/src/scripts/get-user-menu.ts
=> User share page

packages/frontend/src/pages/gallery/post.vue
=> feat: gallery qr code share

packages/frontend/src/components/MkPostForm.vue
=> fix: 投稿フォームから連合なしダイレクトができない問題

packages/frontend/src/components/MkQrcode.vue, packages/frontend/src/os.ts, packages/frontend/src/pages/follow-me.vue, packages/frontend/src/pages/gallery/post.vue, packages/frontend/src/pages/page.vue
=> feat: page qrcode

packages/backend/assets/redoc.html
APIドキュメントでRedocの代わりにscalarを利用する
=> feat: use scalar instead of redoc

packages/frontend/src/components/MkPostForm.vue
- 投稿フォーム上からボタンの数を減らした
- 未使用の関数を削除
=> refactor(frontend): MkPostForm

locales/en-US.yml, locales/index.d.ts, locales/ja-JP.yml
ウィジェット追加メニューでロケールを追加し忘れていた問題を修正
=> fix: missing locale

CHANGELOG_engawa.md, locales/en-US.yml, locales/index.d.ts, locales/ja-JP.yml, packages/backend/migration/1721299883211-AddIsIndexable.js, packages/backend/src/core/NoteCreateService.ts, packages/backend/src/core/NoteUpdateService.ts, packages/backend/src/core/SearchService.ts, packages/backend/src/core/activitypub/ApRendererService.ts, packages/backend/src/core/activitypub/misc/contexts.ts, packages/backend/src/core/activitypub/models/ApPersonService.ts, packages/backend/src/core/activitypub/type.ts, packages/backend/src/core/entities/UserEntityService.ts, packages/backend/src/models/User.ts, packages/backend/src/models/UserProfile.ts, packages/backend/src/models/json-schema/user.ts, packages/backend/src/server/api/endpoints/i/update.ts, packages/cherrypick-js/src/autogen/types.ts, packages/frontend/src/pages/settings/privacy.vue
kmyblueのindexableプロパティを追加
連合的なあれ
TODO: 本体でもisIndexableを考慮する必要がある
=> feat: add isindexable

packages/frontend/src/ui/_common_/navbar-for-mobile.vue, packages/frontend/src/ui/_common_/navbar.vue
Deck UIのナビゲーションバーをFriendly風に
close #97
=> change: Deck UIのナビゲーションバーのスタイル調整

.github/workflows/lint.yml, packages/backend/biome.json, packages/backend/package.json, packages/cherrypick-js/biome.json, packages/cherrypick-js/package.json, packages/frontend/biome.json, packages/frontend/package.json, packages/sw/biome.json, packages/sw/package.json, pnpm-lock.yaml
Linter/Formatterの両方にBiomeを導入
close #103
=> enhance: Introduce Biome.js

packages/backend/src/core/activitypub/ApInboxService.ts
ApInboxService.tsでtargetUriがundefinedだったためにエラーが起きていたのを修正
=> fix: target uri is undefined

packages/frontend/src/components/MkReactionsViewer.reaction.vue
リアクションが盗めないことがあるのを修正
バグなので
直ったか確かめられてないので実際にプロダクション環境で確かめるしかない
(Codespaceだと401になる。なんで？)
=> fix?: reaction stealer

CHANGELOG_engawa.md, packages/frontend/src/pages/settings/index.vue
=> fix: 設定ページの下部に不要なスペースがあった問題

CHANGELOG_engawa.md, packages/backend/src/core/SearchService.ts
=> feat: 検索対象にCWを含むように

CHANGELOG_engawa.md, packages/backend/src/core/activitypub/models/ApPersonService.ts
=> fix: indexable

packages/backend/src/core/SearchService.ts
=> isIndexableの検索クエリを変更

CHANGELOG_engawa.md, packages/backend/src/server/api/endpoints/antennas/notes.ts
=> fix: アンテナで正しくindexableがfalseなユーザーを検索から除外できるように

locales/index.d.ts, locales/ja-JP.yml, packages/backend/src/server/api/endpoints/notes/events/search.ts, packages/backend/src/server/api/endpoints/users/search.ts
ユーザー検索とイベント検索でもindexableを考慮するように
プライバシーの尊重
=> enhance: ユーザー検索とイベント検索でもindexableを尊重するように

CHANGELOG_engawa.md, packages/backend/src/server/api/endpoints/hashtags/search.ts, packages/cherrypick-js/etc/cherrypick-js.api.md, packages/cherrypick-js/src/streaming.types.ts, packages/frontend/src/pages/tag.vue
ハッシュタグをストリーミングで流すように
close #174
=> feat: ハッシュタグTL
